import pyautogui
import time
time.sleep(5)
pyautogui.typewrite('-23')
pyautogui.press('enter')
pyautogui.typewrite('5')
pyautogui.press('enter')
pyautogui.typewrite('0')
pyautogui.press('enter')
pyautogui.typewrite('1')
pyautogui.press('enter')
pyautogui.typewrite('-9')
pyautogui.press('enter')
pyautogui.typewrite('-11')
pyautogui.press('enter')
pyautogui.typewrite('6')
pyautogui.press('enter')
pyautogui.typewrite('2')
pyautogui.press('enter')
pyautogui.typewrite('3')
pyautogui.press('enter')
