# STRING :- IS A DATA TYPE THAT STORE A SEQUENCE OF CHARACTER
#STRING CAN BE WRITTEN INSIDE " " OR ' ' OR  """ """

# HOW TO WRITE A SENTENCE/WORD  ON NEXT LINE
str1="MY NAME IS MAYURESH\nI AM 18 YEAR OLD "
print(str1)
# IN ABOVE MENTIONED CODE WE USE \n TO PRINT A STRING ON NEXT LINE

# HOW TO CREATE A SPACE BETWEEN TWO SENTENCES
str2="MY NAME IS AAKASH\tI AM 18 YEAR OLD"
print(str2)
# IN ABOVE MENTIONED CODE WE USE \t TO CREATE A SPACE BETWEEN TWO SENTENCES IN OUT PUT

# OPERATION ON STRING

# 1. CONCATENATION :- COMBINING TWO STRING TOGETHER
str3="Mayuresh"
str4="Teli"
finalstr=str3+str4
print(finalstr)

# 2. TO FIND LENGTH OF STRING
# WE USE FUNCTION len TO FIND THE LENGTH OF STRING
print(len(finalstr))
# IN LENGTH OF STRING WE CONSIDER ALL CHARACTER AND SPACE PRESENT IN THE STRING

# INDEXING
"""" -9,-8,-7,-6,-5,-4,-3,-2,-1
     ABCD EFGH
     012345678
     AS SHOWN ABOVE  positive INDEXING OF STRING START FROM 0 
     AS SHOWN ABOVE  NEGATIVE INDEXING OF STRING START FROM -1
     AND THE SPACE IN STRING IS ALSO ASSIGN WITH AN INDEX NUMBER"""
     
str5="ABCD EFGH"
print(str5[0])
print(str5[-1])
# SLICING :- ACCESING PART OF STRING 
# str[ starting index:ending index ]
print(str3[0:8])
print(str3[0:len(str3)])
print(str3[ :8])#[0:8]
print(str3[0: ])#[0:len(str3)]
print(str5[-1:-6])